name: beautech-ci-cd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Build code"
        run: |
          cd beautechlink
          npm ci
          npm run build

  depCheck:
    runs-on: ubuntu-latest
    needs: build-code  # Ensures depCheck runs only after build-code
    steps:
      - uses: actions/checkout@v2
      - name: "Set up JDK 1.8"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: "Run Dependency Check"
        run: |
          cd beautechlink  # Make sure you navigate to the correct directory
          mvn --settings ../.mvn/settings.xml clean install
