name: beautech-ci-cd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout-code-from-repo

  build-code:
    runs-on: ubuntu-latest
    needs: [ checkout-code ]
    steps:
      - name: "Build code"
        run: |
          cd beautechlink  # Navigate to your app folder
          npm ci
          npm run build
