name: beautech-ci-cd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Check current directory"
        run: pwd  # Check where we are
      - name: "List contents of current directory"
        run: ls -la  # List contents of the current directory
      - name: "Build code"
        run: |
          cd beautechlink  # Change to the directory where your pom.xml is located
          pwd  # Print the current working directory to confirm
          ls -la  # List contents of the current directory
          mvn clean install  # Run Maven command

  depCheck:
    runs-on: ubuntu-latest
    needs: build-code  # Ensure this runs after the build-code job
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: dependencyCheckAnalyze
