name: beautech-ci-cd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: checkout-code-from-repo
      - run: echo "Checking out code"

  build-code:
    runs-on: ubuntu-latest
    needs: [ checkout-code ]
    steps:
      - uses: actions/checkout@v2
      - name: "Build code"
        run: |
          npm ci
          npm run build
      
