name: beautech-ci-cd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout-code-from-repo

      - name: Prints Working directory
        run: pwd
      - name: List directory contents for debugging
        run: ls -la

  build-code:
    runs-on: ubuntu-latest
    needs: [ checkout-code ]
    steps:
      - name: "Build code"
        run: |
          # cd beautechlink  Ensure this folder exists
          npm install
          npm run build
