name: beautech-ci-cd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Check current directory"
        run: pwd  # Check where we are
      - name: "List contents of current directory"
        run: ls -la  # List contents of the current directory
      - name: "Build code"
        run: |
          cd beautechlink
          npm ci
          npm run build
